packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/@eden3/*'
  - 'adapters/*'

# Catalog disabled for compatibility
# catalog:
#   "@types/node": "^20.0.0"
#   typescript: "^5.0.0"
#   turbo: "^2.0.0"
#   zod: "^3.22.0"