packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/@eden3/*'
  - 'adapters/*'

# Catalog for package discovery
catalog:
  "@types/node": "^20.0.0"
  typescript: "^5.0.0"
  turbo: "^2.0.0"
  zod: "^3.22.0"
  "@nestjs/core": "^10.0.0"
  "@nestjs/common": "^10.0.0"
  "next": "^14.0.0"
  "react": "^18.0.0"
  "react-dom": "^18.0.0"