services:
  - type: web
    name: eden3-api
    env: node
    plan: starter
    autoDeploy: true
    region: frankfurt
    buildCommand: "npm ci && npm run build"
    startCommand: "node dist/src/main.js"
    healthCheckPath: "/health"
    # Render sets PORT for you. Do NOT hardcode.
    envVars:
      - key: NODE_ENV
        value: production
      - key: FORCE_HTTPS
        value: "0"
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SENTRY_DSN
        sync: false